trigger:
- master
- release/*
- beta/*
- test/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install
    npm run test
    npm run build

- task: Npm@1
  displayName: 'npm publish beta (conditionally)'
  inputs:
    command: custom
    verbose: false
    customCommand: 'publish --tag beta'
    publishEndpoint: npm
    customEndpoint: npm
  continueOnError: true
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/beta'))

- task: Npm@1
  displayName: 'npm publish release (conditionally)'
  inputs:
    command: publish
    verbose: false
    publishEndpoint: npm
    customEndpoint: npm
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
